import { TariffFlag } from './types';

export const TARIFF_FLAGS: Record<TariffFlag, { label: string; extraPer100kWh: number; color: string; bg: string }> = {
  verde: { label: 'Bandeira Verde', extraPer100kWh: 0, color: 'text-green-600 dark:text-green-400', bg: 'bg-green-100 dark:bg-green-900/30' },
  amarela: { label: 'Bandeira Amarela', extraPer100kWh: 1.88, color: 'text-yellow-600 dark:text-yellow-400', bg: 'bg-yellow-100 dark:bg-yellow-900/30' },
  vermelha1: { label: 'Bandeira Vermelha P1', extraPer100kWh: 4.46, color: 'text-red-500 dark:text-red-400', bg: 'bg-red-100 dark:bg-red-900/30' },
  vermelha2: { label: 'Bandeira Vermelha P2', extraPer100kWh: 7.87, color: 'text-red-700 dark:text-red-300', bg: 'bg-red-200 dark:bg-red-900/50' },
};

export const COMMON_APPLIANCES = [
  { name: 'Amaciador de Carne 1/2 CV', quantity: 1, power: 368, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Amaciador de Carne 1/3 CV', quantity: 1, power: 245, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Amplificador de Som 1000W', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Amplificador de Som 150W', quantity: 1, power: 150, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Amplificador de Som 1600W', quantity: 1, power: 1600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Amplificador de Som 2000W', quantity: 1, power: 2000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Amplificador de Som 200W', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Amplificador de Som 2600W', quantity: 1, power: 2600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Amplificador de Som 500W', quantity: 1, power: 500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Amplificador de Som 790W', quantity: 1, power: 790, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Amplificador de Som 8000W', quantity: 1, power: 8000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Amplificador de Som 90W', quantity: 1, power: 90, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Amplificador Radio Transmissor', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho Antena Parabolica', quantity: 1, power: 140, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Audiometria', quantity: 1, power: 720, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Blu-ray', quantity: 1, power: 20, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Depilação', quantity: 1, power: 40, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Eletrocardiograma', quantity: 1, power: 1200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Eletroencefalograma', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Estimulacao', quantity: 1, power: 600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Infra Vermelho', quantity: 1, power: 60, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Massagem 1000W', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Massagem 100W', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Massagem 200W', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Massagem 30W', quantity: 1, power: 30, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Massagem 500W', quantity: 1, power: 500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Massagem 700W', quantity: 1, power: 700, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Massagem Pequeno', quantity: 1, power: 60, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Raio X - 300 a 500MA', quantity: 1, power: 30000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho de Ultra-som C/video', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho DVD', quantity: 1, power: 60, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho Fisioterapico', quantity: 1, power: 600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho Oftamologico', quantity: 1, power: 980, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aparelho Para TV a Cabo', quantity: 1, power: 80, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aquecedor de Agua (boiler 100 e 250 Lts)', quantity: 1, power: 2000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aquecedor de Agua (boiler 300 Lts)', quantity: 1, power: 4500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aquecedor de Agua (boiler 400 Lts)', quantity: 1, power: 6000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aquecedor de Agua (boiler 50 e 75 Lts)', quantity: 1, power: 1200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aquecedor de Agua (boiler 500 Lts)', quantity: 1, power: 7500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aquecedor de Mamadeira', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 10.000 BTU\'S', quantity: 1, power: 1081, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 10.100 BTU\'S', quantity: 1, power: 980, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 10.500 BTU\'S', quantity: 1, power: 1112, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 12.000 BTU\'S', quantity: 1, power: 1364, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 17.500 BTU\'S', quantity: 1, power: 2080, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 18.000 BTU\'S', quantity: 1, power: 2183, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 18.500 BTU\'S', quantity: 1, power: 1800, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 19.000 BTU\'S', quantity: 1, power: 2060, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 20.200 BTU\'S', quantity: 1, power: 2672, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 20.600 BTU\'S', quantity: 1, power: 2695, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 21.000 BTU\'S', quantity: 1, power: 2800, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 30.000 BTU\'S', quantity: 1, power: 3813, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 7.000 BTU\'S', quantity: 1, power: 817, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 7.100 BTU\'S', quantity: 1, power: 715, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 7.150 BTU\'S', quantity: 1, power: 720, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 7.500 BTU\'S', quantity: 1, power: 880, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 8.000 BTU\'S', quantity: 1, power: 800, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 8.300 BTU\'S', quantity: 1, power: 900, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 8.500 BTU\'S', quantity: 1, power: 927, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar Condicionado - 9.000 BTU\'S', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar condicionado 12.000 BTUs', quantity: 1, power: 1364, hoursPerDay: 8, daysPerMonth: 30 },
  { name: 'Ar Condicionado 36.000btu\'s', quantity: 1, power: 4195, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ar condicionado 9.000 BTUs', quantity: 1, power: 1000, hoursPerDay: 8, daysPerMonth: 30 },
  { name: 'Aspirador de Po Comercial 40L', quantity: 1, power: 1400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aspirador de Po Comercial 80L', quantity: 1, power: 2240, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Aspirador de Po Residencial 22L', quantity: 1, power: 1250, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Assadeira Eletrica Grande', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Assadeira Eletrica Pequena', quantity: 1, power: 500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Auto Falante 500W', quantity: 1, power: 500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Autoclave - Acima de 150 L', quantity: 1, power: 8000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Autoclave - de 101 a 150 L', quantity: 1, power: 6000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Autoclave - de 41 a 60 L', quantity: 1, power: 2000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Autoclave - de 61 a 100 L', quantity: 1, power: 4000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Autoclave 12 L', quantity: 1, power: 1200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Autoclave 13 a 40 L - Média', quantity: 1, power: 1600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Autoclave 21 L', quantity: 1, power: 1600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Autoclave 42 L', quantity: 1, power: 2200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Autoclave Analogica de 19 L', quantity: 1, power: 1750, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Balanca Eletrica', quantity: 1, power: 20, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Balcao Frigorifico Grande', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Balcao Frigorifico Pequeno', quantity: 1, power: 400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Balcao Medio Expositor de Alimentos', quantity: 1, power: 500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Balcao Pequeno Expositor de Salgados', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Banheira de Hidromassagem 400W', quantity: 1, power: 400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Banheira de Hidromassagem 8200W', quantity: 1, power: 8200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Banheira Hidromassagem 4000W', quantity: 1, power: 4000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Barbeador Eletrico', quantity: 1, power: 10, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Batedeira', quantity: 1, power: 100, hoursPerDay: 0.5, daysPerMonth: 8 },
  { name: 'Batedeira Eletrica Grande', quantity: 1, power: 300, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Batedeira Eletrica Pequena', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bebedouro', quantity: 1, power: 70, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bebedouro Grande', quantity: 1, power: 366, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Berço Aquecido', quantity: 1, power: 580, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Berço Térmico', quantity: 1, power: 9600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Betoneira 120 L', quantity: 1, power: 550, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Betoneira 400 L', quantity: 1, power: 1472, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba D\'agua 1.0 HP', quantity: 1, power: 746, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba D\'agua 1/2 HP', quantity: 1, power: 373, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba D\'agua 1/3 HP', quantity: 1, power: 248, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba D\'agua 1/4 HP', quantity: 1, power: 187, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba D\'agua 10.0 HP', quantity: 1, power: 7460, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba D\'agua 15.0 HP', quantity: 1, power: 11190, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba D\'agua 2.0 HP', quantity: 1, power: 1492, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba D\'agua 3.0 HP', quantity: 1, power: 2238, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba D\'agua 3/4 HP', quantity: 1, power: 560, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba D\'agua 4 HP', quantity: 1, power: 2984, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba D\'agua 40 CV', quantity: 1, power: 29840, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba D\'agua 45 CV', quantity: 1, power: 33570, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba D\'agua 5.0 HP', quantity: 1, power: 3730, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba D\'agua 7.5 HP', quantity: 1, power: 5595, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba d\'água 1/2 HP', quantity: 1, power: 373, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba de Aquario', quantity: 1, power: 10, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Bomba de Combustivel de Posto', quantity: 1, power: 500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Cabine Ura', quantity: 1, power: 490, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Cadeira de Dentista', quantity: 1, power: 1100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Cadeira de Dentista Simples', quantity: 1, power: 780, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Cafeteira Eletrica', quantity: 1, power: 550, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Cafeteira elétrica', quantity: 1, power: 550, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Cafeteira Eletrica Grande', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Caixa Registradora', quantity: 1, power: 150, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Camara Frigorifica Grande', quantity: 1, power: 52500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Camara Frigorifica Media', quantity: 1, power: 6341, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Camera de Seguranca', quantity: 1, power: 20, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Campainha Residencial', quantity: 1, power: 8, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Carregador de Aparelho Celular', quantity: 1, power: 10, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Carregador de Bateria (tunga)', quantity: 1, power: 600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Carregador de Bateria 2kw', quantity: 1, power: 2000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Carregador de celular', quantity: 1, power: 10, hoursPerDay: 3, daysPerMonth: 30 },
  { name: 'Central de Alarmes 1kw', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Central de Ar Condicionado de 10 TR - Média', quantity: 1, power: 13640, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Central de Ar Condicionado de 15 TR - Média', quantity: 1, power: 20460, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Central de Ar Condicionado de 2 TR - Média', quantity: 1, power: 2728, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Central de Ar Condicionado de 20 TR - Média', quantity: 1, power: 27280, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Central de Ar Condicionado de 5 TR - Média', quantity: 1, power: 6820, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Central Telefonica 2 Linhas', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Central Telefonica 6 Linhas', quantity: 1, power: 300, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Cerca Eletrica', quantity: 1, power: 8000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Chapa ou Prancha de Alisamento', quantity: 1, power: 300, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Chocadeira Pequena', quantity: 1, power: 300, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Churrasqueira Eletrica Grande', quantity: 1, power: 3800, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Churrasqueira Eletrica Pequena', quantity: 1, power: 2000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Chuveiro elétrico', quantity: 1, power: 5500, hoursPerDay: 0.5, daysPerMonth: 30 },
  { name: 'Chuveiro Eletrico Classe a', quantity: 1, power: 2400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Chuveiro Eletrico Classe B Média', quantity: 1, power: 2950, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Chuveiro Eletrico Classe C Média', quantity: 1, power: 4050, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Chuveiro Eletrico Classe D Média', quantity: 1, power: 5150, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Chuveiro Eletrico Classe e Média', quantity: 1, power: 6250, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Chuveiro Eletrico Classe F Média', quantity: 1, power: 7350, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Chuveiro Eletrico Classe G', quantity: 1, power: 7900, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Cilindro 1 CV', quantity: 1, power: 736, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Circuito Interno de TV Simples', quantity: 1, power: 50, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Circulador de Ar Grande', quantity: 1, power: 540, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Circulador de Ar Medio', quantity: 1, power: 250, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Circulador de Ar Pequeno', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Claves', quantity: 1, power: 1600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Climatizador', quantity: 1, power: 1400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Compressor de Ar 25L 2HP', quantity: 1, power: 1492, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Compressor de Ar 425L 15HP', quantity: 1, power: 11190, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Compressor de Ar 8L 1HP', quantity: 1, power: 736, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Computador', quantity: 1, power: 250, hoursPerDay: 8, daysPerMonth: 30 },
  { name: 'Conjunto de Som 140W', quantity: 1, power: 140, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Conjunto de Som Pequeno 100W', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Conjunto de Som Port 60W', quantity: 1, power: 60, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Conjunto de Som Residencial 160W', quantity: 1, power: 160, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Corneta 100W', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Cortador de Frios', quantity: 1, power: 500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Cortador de Grama Grande', quantity: 1, power: 2500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Cortador de Grama Média', quantity: 1, power: 1300, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Cortina de Ar Pequena', quantity: 1, power: 400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Data Show', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Detector de Metal', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Elevador Para Carro', quantity: 1, power: 2944, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Elevador Predial 10 Pessoas 15vc', quantity: 1, power: 11040, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Elevador Predial 12 Pessoas 20CV', quantity: 1, power: 14720, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Elevador Predial 4 Pessoas 10CV', quantity: 1, power: 7360, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Elevador Predial 6 Pessoas 12CV', quantity: 1, power: 8832, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Enceradeira Industrial 1HP', quantity: 1, power: 746, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Enceradeira Industrial 2HP', quantity: 1, power: 1492, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Enceradeira Residencial', quantity: 1, power: 400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Equalizador de Som', quantity: 1, power: 210, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Escada Rolante', quantity: 1, power: 10000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Esmeril 1 CV', quantity: 1, power: 736, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Esmeril 1/2 CV', quantity: 1, power: 368, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Esmeril 2 CV', quantity: 1, power: 1472, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Espremedor de Laranjas', quantity: 1, power: 248, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Estabilizador de Tensao', quantity: 1, power: 300, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Esteira Eletrica 80W', quantity: 1, power: 80, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Esteira Ergometrica', quantity: 1, power: 670, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Esterelizador', quantity: 1, power: 500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Estufa', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Estufa de Salgados', quantity: 1, power: 150, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Exaustor Grande', quantity: 1, power: 400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Exaustor Pequeno (sugar)', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Fatiador', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Fax', quantity: 1, power: 10, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ferro de passar automático', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 8 },
  { name: 'Ferro de Solda Grande', quantity: 1, power: 550, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ferro de Solda Medio', quantity: 1, power: 250, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ferro de Solda Pequeno', quantity: 1, power: 80, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ferro Eletrico Automatico 1200W', quantity: 1, power: 1200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ferro Eletrico Automatico 700W', quantity: 1, power: 700, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ferro Eletrico Automatico a Vapor', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ferro Eletrico Manual', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Ferro Eletrico Semi Automatico', quantity: 1, power: 750, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Fliperama', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Foco Cirurgico', quantity: 1, power: 420, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Fogao Eletrico 2 Bocas', quantity: 1, power: 2250, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Fogao Eletrico 4 Bocas', quantity: 1, power: 2750, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Fogao Eletrico 4 Chapas', quantity: 1, power: 7400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Fogao Eletrico 6 Bocas', quantity: 1, power: 3600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Forno de Microondas 20 L Médio', quantity: 1, power: 950, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Forno de Microondas 30 L Médio', quantity: 1, power: 1110, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Forno de Microondas 38 L', quantity: 1, power: 1500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Forno de Microondas 40 L', quantity: 1, power: 1700, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Forno Eletrico a Resistencia', quantity: 1, power: 1500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Forno Eletrico de Padaria 14500W', quantity: 1, power: 14500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Forno Eletrico de Padaria 52200W', quantity: 1, power: 52200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Forno Eletrico p/ Ceramica Grande', quantity: 1, power: 8500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Forno Eletrico p/ Ceramica Medio', quantity: 1, power: 6000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Forno Eletrico p/ Ceramica Pequeno', quantity: 1, power: 2000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Forrageira', quantity: 1, power: 736, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Fotopolimerizador', quantity: 1, power: 95, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Freezer Horizontal', quantity: 1, power: 150, hoursPerDay: 24, daysPerMonth: 30 },
  { name: 'Freezer Horizontal 170 L', quantity: 1, power: 120, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Freezer Horizontal 200 L', quantity: 1, power: 150, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Freezer Horizontal 320 e 330 L', quantity: 1, power: 300, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Freezer Horizontal 414L', quantity: 1, power: 400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Freezer Horizontal 480 e 660 L', quantity: 1, power: 400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Freezer Vertical', quantity: 1, power: 90, hoursPerDay: 24, daysPerMonth: 30 },
  { name: 'Freezer Vertical 120 L', quantity: 1, power: 120, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Freezer Vertical 180 L', quantity: 1, power: 120, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Freezer Vertical 220L', quantity: 1, power: 265, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Freezer Vertical 280 L', quantity: 1, power: 265, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Freezer Vertical 360 L', quantity: 1, power: 265, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Frigobar', quantity: 1, power: 80, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Fritadeira (Air Fryer)', quantity: 1, power: 1500, hoursPerDay: 0.5, daysPerMonth: 15 },
  { name: 'Fritadeira Grande', quantity: 1, power: 5000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Fritadeira Media', quantity: 1, power: 3000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Fritadeira Pequena', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Furadeira Grande', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Furadeira Pequena', quantity: 1, power: 350, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Geladeira', quantity: 1, power: 150, hoursPerDay: 24, daysPerMonth: 30 },
  { name: 'Geladeira 01 Porta 253L', quantity: 1, power: 80, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Geladeira 01 Porta 310L', quantity: 1, power: 120, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Geladeira 2 Portas 414L', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Geladeira 216 Litros', quantity: 1, power: 80, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Geladeira 254 Litros', quantity: 1, power: 80, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Geladeira 280 Litros', quantity: 1, power: 105, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Geladeira 310 Litros', quantity: 1, power: 120, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Geladeira 324 Litros', quantity: 1, power: 120, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Geladeira Duplex', quantity: 1, power: 105, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Geladeira Duplex e Triplex 430L', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Geladeira Industrial', quantity: 1, power: 550, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Gelopar', quantity: 1, power: 380, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Grelha Eletrica Grande', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Grelha Eletrica Pequena', quantity: 1, power: 500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Grill/chapa', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Guincho Eletrico C/motor de 1CV', quantity: 1, power: 736, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Impressora 200W', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Impressora 600W', quantity: 1, power: 600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Interfone', quantity: 1, power: 40, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl 11W', quantity: 1, power: 11, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl 16W', quantity: 1, power: 16, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl 20W', quantity: 1, power: 20, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl 25W', quantity: 1, power: 25, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl 32W', quantity: 1, power: 32, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl 400W', quantity: 1, power: 400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl 40W', quantity: 1, power: 40, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl 45W', quantity: 1, power: 45, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl 60W', quantity: 1, power: 60, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl Comp 13W', quantity: 1, power: 13, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl Comp 15W', quantity: 1, power: 15, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl Comp 18W', quantity: 1, power: 18, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl Comp 20W', quantity: 1, power: 20, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl Comp 23W', quantity: 1, power: 23, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl Comp 27W', quantity: 1, power: 27, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl Comp 7W', quantity: 1, power: 7, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl Comp 9W', quantity: 1, power: 9, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Fl Ho 110W', quantity: 1, power: 110, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Incand 1000W', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Incand 100W', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Incand 150W', quantity: 1, power: 150, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Incand 160W', quantity: 1, power: 160, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Incand 200W', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Incand 20W', quantity: 1, power: 20, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Incand 250W', quantity: 1, power: 250, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Incand 25W', quantity: 1, power: 25, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Incand 300W', quantity: 1, power: 300, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Incand 40W', quantity: 1, power: 40, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Incand 500W', quantity: 1, power: 500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Incand 55W', quantity: 1, power: 55, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Incand 60W', quantity: 1, power: 60, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Incand 75W', quantity: 1, power: 75, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Sinaliz. Garagem', quantity: 1, power: 150, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor de Mercurio 1000W', quantity: 1, power: 1090, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor de Mercurio 125W', quantity: 1, power: 139, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor de Mercurio 2000', quantity: 1, power: 2090, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor de Mercurio 250W', quantity: 1, power: 288, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor de Mercurio 400W', quantity: 1, power: 438, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor de Mercurio 500W', quantity: 1, power: 538, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor de Mercurio 700W', quantity: 1, power: 738, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor de Mercurio 80W', quantity: 1, power: 94, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor Sodio 1000W', quantity: 1, power: 1090, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor Sodio 100W', quantity: 1, power: 114, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor Sodio 150W', quantity: 1, power: 164, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor Sodio 250W', quantity: 1, power: 288, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor Sodio 350W', quantity: 1, power: 388, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor Sodio 35W', quantity: 1, power: 41, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor Sodio 360W', quantity: 1, power: 398, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor Sodio 400W', quantity: 1, power: 438, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor Sodio 50W', quantity: 1, power: 56, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor Sodio 600W', quantity: 1, power: 600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lamp Vapor Sodio 70W', quantity: 1, power: 84, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada de Luz Infra Vermelha', quantity: 1, power: 150, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada de Luz Ultra Violeta', quantity: 1, power: 150, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Dicroica 25W', quantity: 1, power: 25, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Dicroica 50W', quantity: 1, power: 50, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Dicroica 75W', quantity: 1, power: 75, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Dicroica LED 5W', quantity: 1, power: 5, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Halogena 150W', quantity: 1, power: 150, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Halogena 250W', quantity: 1, power: 250, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Halogena 300W', quantity: 1, power: 300, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Halogena 500W', quantity: 1, power: 500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lâmpada Incandescente 60W', quantity: 1, power: 60, hoursPerDay: 5, daysPerMonth: 30 },
  { name: 'Lampada LED 18W', quantity: 1, power: 18, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lâmpada LED 18W', quantity: 1, power: 18, hoursPerDay: 5, daysPerMonth: 30 },
  { name: 'Lampada LED 24W', quantity: 1, power: 24, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lâmpada LED 9W', quantity: 1, power: 9, hoursPerDay: 5, daysPerMonth: 30 },
  { name: 'Lampada Led, 12W', quantity: 1, power: 12, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Led, 18W Redondo', quantity: 1, power: 18, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Led, 24W Redondo', quantity: 1, power: 24, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Led, 6W Redondo', quantity: 1, power: 6, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Led,12w Redondo', quantity: 1, power: 12, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Mista 1000W', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Mista 160W', quantity: 1, power: 160, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Mista 250W', quantity: 1, power: 250, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Mista 500W', quantity: 1, power: 500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Mista 70W', quantity: 1, power: 70, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Spot LED 12*2w', quantity: 1, power: 24, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Spot LED Lamp 3*2w', quantity: 1, power: 6, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Spot LED Lamp 5*2w', quantity: 1, power: 10, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Spot LED Lamp 7*2w', quantity: 1, power: 14, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Spot LED Lamp 9*2w', quantity: 1, power: 18, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Spot LED Painel Quadrado 12W', quantity: 1, power: 12, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Spot LED Quadrado 24W', quantity: 1, power: 24, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Spot LED Tipo Painel 12W', quantity: 1, power: 12, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Spot LED Tipo Painel 18W', quantity: 1, power: 18, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Spot LED Tipo Painel 24W', quantity: 1, power: 24, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Spot LED Tipo Painel 3W', quantity: 1, power: 3, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lampada Spot LED Tipo Painel 6W', quantity: 1, power: 6, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Leitor Código de Barra', quantity: 1, power: 20, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Liquidificador', quantity: 1, power: 270, hoursPerDay: 0.2, daysPerMonth: 30 },
  { name: 'Liquidificador 150W', quantity: 1, power: 150, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Liquidificador 270W', quantity: 1, power: 270, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lixadeira 2 HP', quantity: 1, power: 1492, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lixadeira Grande', quantity: 1, power: 746, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Lixadeira Pequena', quantity: 1, power: 373, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Acai', quantity: 1, power: 250, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Caca Niquel', quantity: 1, power: 300, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Calcular', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Chopp', quantity: 1, power: 400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Cortar Aluminio', quantity: 1, power: 1500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Cortar Cabelo', quantity: 1, power: 20, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Cortar Legumes', quantity: 1, power: 250, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Costura', quantity: 1, power: 138, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Crepes Suissos', quantity: 1, power: 1800, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Depenar Frango', quantity: 1, power: 800, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Encapar Botoes', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Escrever Eletrica', quantity: 1, power: 140, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Gelo (drops)', quantity: 1, power: 1200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Máquina de lavar 10kg', quantity: 1, power: 1060, hoursPerDay: 1, daysPerMonth: 15 },
  { name: 'Maquina de Lavar Pratos', quantity: 1, power: 1200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Lavar Roupas', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Lavar Roupas 10KG', quantity: 1, power: 1060, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Lavar Roupas 4KG', quantity: 1, power: 184, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Lavar Roupas 5KG', quantity: 1, power: 530, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Lavar Roupas 8KG', quantity: 1, power: 990, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Marcar Cartoes de Loteria', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Plastificacao 1kw', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Plastificacao 2kw', quantity: 1, power: 2000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Refrigerante (post Mix)', quantity: 1, power: 400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Serrar Ossos', quantity: 1, power: 300, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Solda Grande', quantity: 1, power: 12000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Solda Media', quantity: 1, power: 6000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Solda Pequena', quantity: 1, power: 2500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Sorvete Industrial', quantity: 1, power: 1250, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Xerox Grd.', quantity: 1, power: 2800, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina de Xerox Peq.', quantity: 1, power: 1400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina Overlock', quantity: 1, power: 400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquina Pos Para Cartao Credito/debito', quantity: 1, power: 20, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquita Grande', quantity: 1, power: 1400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Maquita Pequena', quantity: 1, power: 620, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Massageador Portatil 60W', quantity: 1, power: 60, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Masseira', quantity: 1, power: 736, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Mesa de Som 48 Canais Pro', quantity: 1, power: 30000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Mesa de Som 48 Canais Simples', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Mesa Para Cerigrafia 1kw', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Micro Computador 160W', quantity: 1, power: 160, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Micro Computador 200W', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Micro Computador 400W', quantity: 1, power: 400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Micro System de Som', quantity: 1, power: 60, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Micro System de Som Com TV', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Micro-ondas 30L', quantity: 1, power: 1110, hoursPerDay: 0.5, daysPerMonth: 30 },
  { name: 'Microscopio', quantity: 1, power: 20, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Mimeografo', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Modeladora', quantity: 1, power: 736, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Moedor de Carne', quantity: 1, power: 320, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 1 CV', quantity: 1, power: 736, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 1.5 CV', quantity: 1, power: 147, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 1/2cv', quantity: 1, power: 368, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 1/3cv', quantity: 1, power: 245, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 1/4cv', quantity: 1, power: 184, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 1/5cv', quantity: 1, power: 147, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 1/6 CV', quantity: 1, power: 123, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 10 CV', quantity: 1, power: 7360, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 100 CV', quantity: 1, power: 73600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 112 CV', quantity: 1, power: 82432, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 12.5 CV', quantity: 1, power: 9200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 125 CV', quantity: 1, power: 92000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 15 CV', quantity: 1, power: 11040, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 2 CV', quantity: 1, power: 1472, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 20 CV', quantity: 1, power: 14720, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 200 CV', quantity: 1, power: 147200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 25 CV', quantity: 1, power: 18400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 3 CV', quantity: 1, power: 2208, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 3/4cv', quantity: 1, power: 552, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 30 CV', quantity: 1, power: 22080, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 4 CV', quantity: 1, power: 2944, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 40 CV', quantity: 1, power: 29440, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 5 1/2 CV', quantity: 1, power: 29440, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 5 CV', quantity: 1, power: 368, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 50 CV', quantity: 1, power: 3680, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 6 CV', quantity: 1, power: 36800, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 60 CV', quantity: 1, power: 4416, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 7 CV', quantity: 1, power: 44160, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 7.5 CV', quantity: 1, power: 5520, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 75 CV', quantity: 1, power: 55200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Motor Eletrico 9 CV', quantity: 1, power: 6624, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Multicorte', quantity: 1, power: 180, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Nebulizador Portatil', quantity: 1, power: 600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Nobreak 1200 Va', quantity: 1, power: 1200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Nobreak 2000 Va (2 Kva)', quantity: 1, power: 2000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Nobreak 600 Va', quantity: 1, power: 600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Notebook', quantity: 1, power: 100, hoursPerDay: 8, daysPerMonth: 30 },
  { name: 'Panela Eletrica', quantity: 1, power: 1200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Pipoqueira', quantity: 1, power: 80, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Pistola de Solda', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Placa Luminosa 10m(2)', quantity: 1, power: 500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Placa Luminosa 2m(2)', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Placa Luminosa 6m(2)', quantity: 1, power: 300, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Plaina 1 CV', quantity: 1, power: 736, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Plaina 3 CV', quantity: 1, power: 2208, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Plaina 5 CV', quantity: 1, power: 3680, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Policorte', quantity: 1, power: 8867, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Politriz (polidora) Angular', quantity: 1, power: 850, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Porta Automatica', quantity: 1, power: 750, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Portao Eletrico 1 Motor', quantity: 1, power: 750, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Portao Eletrico 2 Motores', quantity: 1, power: 1500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Prancha alisadora (Chapinha)', quantity: 1, power: 300, hoursPerDay: 0.5, daysPerMonth: 15 },
  { name: 'Prensa Eletrica P/carimbo', quantity: 1, power: 600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Processador/centrifuga', quantity: 1, power: 460, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Projetor Sharp', quantity: 1, power: 3000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Projetor Simples 400W', quantity: 1, power: 400, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Purificador de Agua', quantity: 1, power: 150, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Radio Amador', quantity: 1, power: 200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Radio Relogio', quantity: 1, power: 40, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Radio Transistorizado', quantity: 1, power: 30, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Radio Tup Acs-10 Stein Telecom', quantity: 1, power: 35, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Raio X', quantity: 1, power: 6000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Raio X - 100 a 200MA', quantity: 1, power: 10000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Raio X Odontologico - 8MA', quantity: 1, power: 1200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Rebobinador de Fita de Video', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Recarregadora de Cartuchos de Impressao', quantity: 1, power: 300, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Refletor 250', quantity: 1, power: 250, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Refletor LED 10 W', quantity: 1, power: 10, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Refrigeracao e Pasteurizacao de Leite', quantity: 1, power: 2000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Refrigerador', quantity: 1, power: 170, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Registradora Eletrica', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Relogio de Ponto', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Sauna Comercial', quantity: 1, power: 12000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Sauna Residencial', quantity: 1, power: 4500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Secador de cabelo', quantity: 1, power: 1200, hoursPerDay: 0.3, daysPerMonth: 15 },
  { name: 'Secador de Cabelo Grande', quantity: 1, power: 1900, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Secador de Cabelo Pequeno', quantity: 1, power: 1200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Secador Roupa Comercial', quantity: 1, power: 5000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Secador Roupa Resid', quantity: 1, power: 1300, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Semaforo', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Serra Circular 2CV', quantity: 1, power: 1472, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Serra Circular 7.5 CV', quantity: 1, power: 5520, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Serra Eletrica', quantity: 1, power: 1000, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Serra Tico-tico 240W', quantity: 1, power: 240, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Serra Tico-tico 600W', quantity: 1, power: 600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Sinalizador de Alarme', quantity: 1, power: 20, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Sorveteira Residencial', quantity: 1, power: 20, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Superozon ou Filtro Similar', quantity: 1, power: 40, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Switch e Roteador', quantity: 1, power: 30, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Tanquinho de Lavar Roupas', quantity: 1, power: 184, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Teclado Sintetizador', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Telefone Sem Fio', quantity: 1, power: 10, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Televisor em Cores 14"', quantity: 1, power: 57, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Televisor em Cores 20"', quantity: 1, power: 80, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Televisor em Cores 29"', quantity: 1, power: 100, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Televisor em Cores 32', quantity: 1, power: 180, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Televisor em Cores 39"', quantity: 1, power: 160, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Televisor em Cores 40', quantity: 1, power: 220, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Televisor em Cores 42"', quantity: 1, power: 280, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Televisor em Cores 52"', quantity: 1, power: 330, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Televisor em Cores 9"', quantity: 1, power: 25, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Televisor em Preto e Branco', quantity: 1, power: 90, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Terminal de Computador', quantity: 1, power: 600, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Termocera', quantity: 1, power: 85, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Torneira Eletrica', quantity: 1, power: 5500, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Torradeira de Pao', quantity: 1, power: 800, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'Transf Forca 10 KVA', quantity: 1, power: 9200, hoursPerDay: 1, daysPerMonth: 30 },
  { name: 'TV 32"', quantity: 1, power: 180, hoursPerDay: 5, daysPerMonth: 30 },
  { name: 'TV 42"', quantity: 1, power: 280, hoursPerDay: 5, daysPerMonth: 30 },
  { name: 'Ventilador / Circulador de Ar', quantity: 1, power: 100, hoursPerDay: 8, daysPerMonth: 30 },
  { name: 'Videogame (Console)', quantity: 1, power: 200, hoursPerDay: 3, daysPerMonth: 30 },
];
